name: 'validate_gpu_provisioning'
description: 'Check GPU availability with retry logic for GitHub Actions runners'
inputs:
  max-retries:
    description: 'Maximum number of retry attempts'
    required: false
    default: '20'  # More retries to handle slow provisioning (20 * 30s = 10 minutes max wait)
  retry-delay:
    description: 'Delay between retries in seconds'
    required: false
    default: '30'  # Longer delay between retries since provisioning can take time
  timeout-minutes:
    description: 'Timeout for GPU validation in minutes'
    required: false
    default: '3'

runs:
  using: 'composite'
  steps:
    - name: Validate GPU provisioning with retry
      shell: bash
      run: |
        MAX_RETRIES=${{ inputs.max-retries }}
        RETRY_DELAY=${{ inputs.retry-delay }}
        RETRY_COUNT=0
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          echo "Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES: Checking GPU availability..."
          
          if nvidia-smi &>/dev/null; then
            echo "✅ GPU successfully provisioned"
            nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv,noheader
            exit 0
          else
            echo "⚠️  GPU not available, retrying in ${RETRY_DELAY} seconds..."
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep $RETRY_DELAY
          fi
        done
        
        echo "❌ Failed to provision GPU after $MAX_RETRIES attempts"
        exit 1

