#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: MIT

"""The wiki-v0.1 tool: lint / index / new / approve.

The binding contract lives in README.md. Everything is markdown with a small
frontmatter block; this tool only validates content against the page contracts
and regenerates the derived index. Standard library only; no timestamps.

Layout it operates on (relative to --root, default: the wiki checkout):
  languages/ kernels/ patterns/ techniques/ docs/  -- the corpus (indexed)
  reference/                                        -- frozen code snapshots: greppable and
                                                       fetchable by id, but NOT listed in the
                                                       index (reached via citing pages)
  staging/                                          -- add-knowledge queue (not corpus)
  index.md                                          -- generated by `index`
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path
from typing import Any

DEFAULT_ROOT = Path(__file__).resolve().parents[1]
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
BEGIN_MARK = "<!-- BEGIN GENERATED -->"
END_MARK = "<!-- END GENERATED -->"
STAGING = "staging"

KIND_DIRS = {
    "language": "languages",
    "kernel": "kernels",
    "technique": "techniques",
    "pattern": "patterns",
    "doc": "docs",
    "reference": "reference",
}
DIR_KINDS = {directory: kind for kind, directory in KIND_DIRS.items()}
KIND_ORDER = ("language", "kernel", "pattern", "technique", "doc", "reference")
# reference pages are corpus (grep/page/lint) but deliberately unlisted in index.md:
# agents reach them via the technique/kernel pages that cite them, or via grep
# hits on symbols that exist only in code. This preserves mediated access.
UNINDEXED_KINDS = ("reference",)

REQUIRED_SECTIONS = {
    # language pages: Overview is required; the rest is topical sections per language
    # (execution, tiles, memory, numerics, traced subset, hints/wrapper).
    "language": ("Overview",),
    "kernel": (
        "What it computes",
        "Computational shape",
        "What dominates performance",
        "Applicable techniques",
        "Where it lives",
    ),
    "technique": ("What it is", "Pattern", "When to use", "Caveats", "Evidence"),
    "pattern": ("Symptom", "Likely causes", "Candidate techniques", "Caveats"),
    "doc": (),  # free-form
    "reference": (),  # frozen code snapshot; free-form
}
BANNED_HEADINGS = ("current state", "open ideas", "tried", "track record")

HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$", re.MULTILINE)
SECTION_RE = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)
EVIDENCE_RE = re.compile(r"^##\s+Evidence\s*$(.*?)(?=^##\s|\Z)", re.MULTILINE | re.DOTALL)
NUMBER_RE = re.compile(r"\d")
# Provenance tag on an evidence bullet: [YYYY-MM, ...] — date mandatory; the rest of
# the tag (arch, toolkit verbatim, N=k sample count) is free text. The date is the
# staleness handle: a measured claim without a date can never expire.
DATE_TAG_RE = re.compile(r"\[20\d{2}-\d{2}(?:[^\]]*)\]")
# Architecture token, either inside the tag or anywhere in the bullet prose.
ARCH_RE = re.compile(r"\b(sm_?\d+|B200|GB200|GB300|H100|H200|GH200|A100|L40S?|RTX\s?\d{4})\b")
# Claim basis grades for technique pages ('measured' may carry detail, e.g.
# 'measured, N=3 kernels'); 'ungraded-batch-1' marks pages that predate grading.
BASIS_RE = re.compile(r"^(source-semantics|measured\b.*|single-observation|ungraded-batch-1)$")


@dataclass
class Lint:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def error(self, where: Any, message: str) -> None:
        self.errors.append(f"{where}: {message}")

    def warn(self, where: Any, message: str) -> None:
        self.warnings.append(f"{where}: {message}")


@dataclass(frozen=True)
class Page:
    slug: str
    path: Path
    data: dict[str, Any]
    body: str
    dir_kind: str | None  # kind implied by the directory; None for staging

    @property
    def staged(self) -> bool:
        return self.dir_kind is None


def rel(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


# ---------------------------------------------------------------- frontmatter


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str] | None:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    data: dict[str, Any] = {}
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return data, "\n".join(lines[index + 1 :]).strip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, separator, raw = line.partition(":")
        if not separator:
            return None
        raw = raw.strip()
        if raw.startswith("[") and raw.endswith("]"):
            data[key.strip()] = [item.strip() for item in raw[1:-1].split(",") if item.strip()]
        else:
            data[key.strip()] = raw
    return None


def load_pages(root: Path, lint: Lint | None = None) -> list[Page]:
    pages: list[Page] = []
    directories = [KIND_DIRS[kind] for kind in KIND_ORDER] + [STAGING]
    for directory in directories:
        base = root / directory
        if not base.is_dir():
            continue
        for path in sorted(base.glob("*.md")):
            if path.name.endswith(".review.md"):
                continue  # review reports live beside staged pages; not pages
            parsed = parse_frontmatter(path.read_text(encoding="utf-8"))
            if parsed is None:
                if lint is not None:
                    lint.error(rel(path, root), "page must start with a '---' frontmatter block")
                continue
            data, body = parsed
            pages.append(Page(slug=path.stem, path=path, data=data, body=body, dir_kind=DIR_KINDS.get(directory)))
    return pages


# ---------------------------------------------------------------- lint


def strip_code_fences(text: str) -> str:
    """Blank out fenced code blocks so '#' code comments are not read as headings."""
    out: list[str] = []
    fenced = False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            fenced = not fenced
            out.append("")
            continue
        out.append("" if fenced else line)
    return "\n".join(out)


def _evidence_bullets(block: str) -> list[str]:
    """Aggregate an Evidence block into logical bullets (continuation lines joined)."""
    bullets: list[str] = []
    current: str | None = None
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or set(stripped) <= {"|", "-", ":", " "}:
            if current is not None:
                bullets.append(current)
                current = None
            continue
        if stripped.startswith(("- ", "* ")) or stripped.startswith("|"):
            if current is not None:
                bullets.append(current)
            current = stripped
        elif current is not None:
            current += " " + stripped
        else:
            current = stripped
    if current is not None:
        bullets.append(current)
    return bullets


def _has_section(headings: list[str], name: str) -> bool:
    low = name.lower()
    return any(h.lower() == low or h.lower().startswith(low + " ") for h in headings)


def _banned(heading: str) -> str | None:
    low = heading.strip().rstrip(":").lower()
    for term in BANNED_HEADINGS:
        if low == term or low.startswith(term + " ") or low.startswith(term + ":"):
            return term
    return None


def lint_page(page: Page, lint: Lint, root: Path) -> None:
    """Validate one page against the README.md page contracts."""
    where = rel(page.path, root)
    data = page.data

    if not SLUG_RE.fullmatch(page.slug):
        lint.error(where, "filename must be a lowercase slug ([a-z0-9._-])")
    if data.get("id") != page.slug:
        lint.error(where, f"id must be '{page.slug}' (the filename stem)")

    kind = data.get("kind")
    if kind not in KIND_DIRS:
        lint.error(where, f"kind must be one of: {', '.join(KIND_ORDER)}")
        kind = None
    elif page.dir_kind is not None and kind != page.dir_kind:
        lint.error(
            where,
            f"kind '{kind}' does not match directory '{KIND_DIRS[page.dir_kind]}/' (expected kind '{page.dir_kind}')",
        )

    if not str(data.get("title", "")).strip() or isinstance(data.get("title"), list):
        lint.error(where, "'title' must be a non-empty string")
    summary = data.get("summary")
    if not isinstance(summary, str) or not summary.strip():
        lint.error(where, "'summary' must be a non-empty one-line string")
    elif "\n" in summary:
        lint.error(where, "'summary' must be a single line")
    body = strip_code_fences(page.body)
    sections = SECTION_RE.findall(body)
    if kind is not None:
        for section in REQUIRED_SECTIONS[kind]:
            if not _has_section(sections, section):
                lint.error(where, f"missing required section '## {section}'")

    for heading in HEADING_RE.findall(body):
        term = _banned(heading)
        if term is not None:
            lint.error(
                where,
                f"banned section heading '{heading}' (working state from an optimization run; see README.md 'Page contracts')",
            )

    if kind == "technique":
        basis = str(data.get("basis", "")).strip()
        if not basis:
            lint.error(
                where,
                "technique pages must declare 'basis:' "
                "(source-semantics | measured[, N=k ...] | single-observation | ungraded-batch-1)",
            )
        elif not BASIS_RE.match(basis):
            lint.error(where, f"unknown basis '{basis}'")
        elif basis == "single-observation" and re.search(r"\b(never|always)\b", body, re.IGNORECASE):
            lint.warn(
                where,
                "single-observation basis but the body uses never/always directives; "
                "scope the claim or upgrade the basis",
            )

    for block in EVIDENCE_RE.findall(body):
        for bullet in _evidence_bullets(block):
            if not NUMBER_RE.search(bullet):
                continue  # no measurement content; tag not required
            if not DATE_TAG_RE.search(bullet):
                lint.error(
                    where,
                    f"Evidence bullet has measurement content but no [YYYY-MM, ...] provenance tag: '{bullet[:90]}'",
                )
            elif not ARCH_RE.search(bullet):
                lint.warn(
                    where,
                    f"Evidence bullet names no architecture (sm_xx / B200 / ...): '{bullet[:90]}'",
                )


def lint_wiki(root: Path) -> tuple[Lint, int]:
    """Lint the whole tree. Returns (lint, page_count)."""
    lint = Lint()
    pages = load_pages(root, lint)
    seen: dict[str, str] = {}
    for page in pages:
        lint_page(page, lint, root)
        where = rel(page.path, root)
        if page.slug in seen:
            prior = seen[page.slug]
            pair = {prior.split("/")[0], where.split("/")[0]}
            if STAGING in pair and len(pair) == 2:
                # a staged page with a corpus id is a PENDING UPDATE, not a collision
                lint.warn(where, f"pending update of '{page.slug}' ({prior}); approve replaces the corpus page")
            else:
                lint.error(where, f"duplicate id '{page.slug}' also defined in {prior}")
        else:
            seen[page.slug] = where
    index_path = root / "index.md"
    expected = render_index(pages, root)
    if not index_path.is_file() or index_path.read_text(encoding="utf-8") != expected:
        lint.error("index.md", "generated index is missing or stale (run: run.py index)")
    return lint, len(pages)


def report(lint: Lint, page_count: int) -> int:
    for error in lint.errors:
        print(f"ERROR {error}")
    for warning in lint.warnings:
        print(f"WARNING {warning}")
    print(f"Checked {page_count} pages: {len(lint.errors)} error(s), {len(lint.warnings)} warning(s)")
    return 1 if lint.errors else 0


# ---------------------------------------------------------------- index


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").strip()


def render_index(pages: list[Page], root: Path) -> str:
    corpus = [page for page in pages if not page.staged]
    lines = [
        "<!--- SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved. --->",
        "",
        "<!--- SPDX-License-Identifier: MIT --->",
        "",
        "# cuTile Knowledge Wiki — index",
        "",
        "Generated by `run.py index`. Do not edit manually. Corpus pages only; `staging/` is not part of the corpus.",
        "`reference/` code snapshots are deliberately unlisted: reach them via the pages that cite them,",
        "or by grep; any snapshot is fetchable by id (`run.py page <id>`).",
        "",
        BEGIN_MARK,
    ]
    for kind in KIND_ORDER:
        if kind in UNINDEXED_KINDS:
            continue
        directory = KIND_DIRS[kind]
        rows = sorted((page for page in corpus if page.dir_kind == kind), key=lambda p: p.slug)
        if not rows:
            continue  # no empty sections in the index
        lines += ["", f"## {directory.capitalize()}", "", "| id | title | summary |", "| --- | --- | --- |"]
        for page in rows:
            row = (
                f"| [{page.slug}]({directory}/{page.slug}.md)"
                f" | {_cell(page.data.get('title', ''))}"
                f" | {_cell(page.data.get('summary', ''))}"
            )
            lines.append(row + " |")
    lines += ["", END_MARK, ""]
    return "\n".join(lines)


def write_index(root: Path) -> bool:
    """Regenerate index.md; returns True if the file changed."""
    content = render_index(load_pages(root), root)
    path = root / "index.md"
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


# ---------------------------------------------------------------- new (scaffolder)


def scaffold_text(kind: str, slug: str) -> str:
    lines = [
        "---",
        f"id: {slug}",
        f"kind: {kind}",
        "title: TODO",
        "summary: TODO one-line summary",
        "---",
        "",
        "<!--- SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved. --->",
        "",
        "<!--- SPDX-License-Identifier: MIT --->",
        "",
        "# TODO title",
    ]
    for section in REQUIRED_SECTIONS[kind]:
        lines += ["", f"## {section}", "", "TODO."]
    if not REQUIRED_SECTIONS[kind]:
        lines += ["", "TODO free-form body."]
    return "\n".join(lines) + "\n"


def scaffold(root: Path, kind: str, slug: str) -> int:
    if kind not in KIND_DIRS:
        print(f"ERROR unknown kind '{kind}' (expected: {', '.join(KIND_ORDER)})", file=sys.stderr)
        return 2
    if not SLUG_RE.fullmatch(slug):
        print("ERROR id must be a lowercase slug ([a-z0-9._-])", file=sys.stderr)
        return 2
    target = root / STAGING / f"{slug}.md"
    if target.exists():
        print(f"ERROR {rel(target, root)} already exists", file=sys.stderr)
        return 1
    corpus_target = root / KIND_DIRS[kind] / f"{slug}.md"
    if corpus_target.exists():
        print(f"ERROR {rel(corpus_target, root)} already exists in the corpus", file=sys.stderr)
        return 1
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(scaffold_text(kind, slug), encoding="utf-8")
    print(f"WROTE {rel(target, root)}")
    return 0


# ---------------------------------------------------------------- query (read-side)

CORPUS_DIRS = tuple(KIND_DIRS.values())


def cmd_grep(root: Path, patterns: list[str], ignore_case: bool) -> int:
    """Regex search across corpus page bodies; path:line:text output; grep exit codes."""
    flags = re.IGNORECASE if ignore_case else 0
    try:
        compiled = [re.compile(p, flags) for p in patterns]
    except re.error as exc:
        print(f"ERROR bad regex: {exc}", file=sys.stderr)
        return 2
    hit = False
    for directory in CORPUS_DIRS:
        for path in sorted((root / directory).glob("*.md")):
            for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
                if all(rx.search(line) for rx in compiled):
                    print(f"{rel(path, root)}:{lineno}:{line.strip()}")
                    hit = True
    return 0 if hit else 1


def cmd_page(root: Path, slug: str, summary_only: bool) -> int:
    """Fetch a corpus page by id, searching all kind directories."""
    for directory in CORPUS_DIRS:
        path = root / directory / f"{slug}.md"
        if path.is_file():
            text = path.read_text(encoding="utf-8")
            if summary_only:
                parsed = parse_frontmatter(text)
                if parsed:
                    data, _ = parsed
                    print(f"{slug} [{data.get('kind', '?')}] {data.get('summary', '')}")
                    return 0
            print(text)
            return 0
    # suggestions by token overlap
    tokens = set(re.split(r"[-_.]", slug))
    scored = []
    for directory in CORPUS_DIRS:
        for path in (root / directory).glob("*.md"):
            other = path.stem
            overlap = len(tokens & set(re.split(r"[-_.]", other)))
            if overlap:
                scored.append((-overlap, other))
    print(f"ERROR no page with id '{slug}'", file=sys.stderr)
    for _, name in sorted(scored)[:5]:
        print(f"  did you mean: {name}", file=sys.stderr)
    return 1


# ---------------------------------------------------------------- approve


def approve(root: Path, slug: str) -> int:
    staged_path = root / STAGING / f"{slug}.md"
    if not staged_path.is_file():
        print(f"ERROR {rel(staged_path, root)} not found", file=sys.stderr)
        return 1
    parsed = parse_frontmatter(staged_path.read_text(encoding="utf-8"))
    if parsed is None:
        print(f"ERROR {rel(staged_path, root)}: page must start with a '---' frontmatter block", file=sys.stderr)
        return 1
    data, body = parsed
    page = Page(slug=slug, path=staged_path, data=data, body=body, dir_kind=None)
    gate = Lint()
    lint_page(page, gate, root)
    kind = data.get("kind")
    target = root / KIND_DIRS[kind] / f"{slug}.md" if kind in KIND_DIRS else None
    replacing = target is not None and target.exists()
    if gate.errors:
        for error in gate.errors:
            print(f"ERROR {error}")
        print(f"REFUSED {rel(staged_path, root)}: {len(gate.errors)} lint error(s); page not moved")
        return 1

    assert target is not None
    target.parent.mkdir(parents=True, exist_ok=True)
    staged_path.rename(target)
    print(
        f"APPROVED {rel(staged_path, root)} -> {rel(target, root)}" + (" (replaced existing page)" if replacing else "")
    )
    review = root / STAGING / f"{slug}.review.md"
    if review.is_file():
        review.unlink()
        print(f"DELETED {rel(review, root)}")
    if write_index(root):
        print("WROTE index.md")
    lint, page_count = lint_wiki(root)
    return report(lint, page_count)


# ---------------------------------------------------------------- main


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT, help="wiki root (for tests)")
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("lint", help="validate page contracts, evidence rules, and index freshness")
    grep_parser = commands.add_parser("grep", help="regex search across corpus pages: grep <pattern> [pattern...] [-i]")
    grep_parser.add_argument("patterns", nargs="+")
    grep_parser.add_argument("-i", "--ignore-case", action="store_true")
    page_parser = commands.add_parser("page", help="print a corpus page by id: page <id> [--summary]")
    page_parser.add_argument("slug")
    page_parser.add_argument("--summary", action="store_true")
    commands.add_parser("index", help="regenerate index.md")
    new_parser = commands.add_parser("new", help="scaffold a staging candidate: new <kind> <id>")
    new_parser.add_argument("page_kind", choices=sorted(KIND_DIRS))
    new_parser.add_argument("slug", metavar="id")
    approve_parser = commands.add_parser("approve", help="move a staged page into the corpus (human step)")
    approve_parser.add_argument("slug", metavar="id")
    args = parser.parse_args(argv)
    root = args.root.resolve()

    if args.command == "lint":
        lint, page_count = lint_wiki(root)
        return report(lint, page_count)
    if args.command == "index":
        if write_index(root):
            print("WROTE index.md")
        return 0
    if args.command == "new":
        return scaffold(root, args.page_kind, args.slug)
    if args.command == "grep":
        return cmd_grep(root, args.patterns, args.ignore_case)
    if args.command == "page":
        return cmd_page(root, args.slug, args.summary)
    if args.command == "approve":
        return approve(root, args.slug)
    raise AssertionError(args.command)


if __name__ == "__main__":
    raise SystemExit(main())
